CREATE TABLE `uuid` (
  `uuid` VARCHAR(40) BINARY not null DEFAULT '' COMMENT 'UUID',
  `used` TINYINT(3) NOT NULL DEFAULT 0 COMMENT '是否使用：0未使用，1已使用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '说明备注',
  `createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY `uuid` (`uuid`),
  KEY `used` (`used`)
) ENGINE = InnoDB, CHARSET = utf8, COMMENT = 'UUID';