<?php

namespace Tools\Pattern\Behavioral\State;

class ContextOrder extends StateOrder
{
    public function getState(): StateOrder
    {
        return static::$state;
    }
    
    public function setState(StateOrder $state)
    {
        static::$state = $state;
    }
    
    public function done()
    {
        static::$state->done();
    }
    
    public function getStatus()
    {
        return static::$state->getStatus(); // TODO: Change the autogenerated stub
    }
}
